import { sidebar } from 'vuepress-theme-hope'

export const zhSidebar = sidebar({
  '/java/': [{
    text: 'Java基础',
    prefix: 'basic/',
    collapsible: true,
    children: [
      'java-basic-oop',
      'java-basic-lan-basic',
      'java-basic-lan-sum',
      'java-basic-x-generic',
      'java-basic-x-annotation',
      'java-basic-x-exception',
      'java-basic-x-reflection',
      'java-advanced-spi',
    ]
  }, {
    text: 'Java集合',
    prefix: 'collection/',
    collapsible: true,
    children: [
      'java-collection-all',
      'java-collection-ArrayList',
      'java-collection-LinkedList',
      'java-collection-Queue&Stack',
      'java-collection-PriorityQueue',
      'java-map-HashMap&HashSet',
      'java-map-LinkedHashMap&LinkedHashSet',
      'java-map-TreeMap&TreeSet',
      'java-map-WeakHashMap',
    ]
  }, {
    text: 'Java多线程与并发',
    prefix: 'thread/',
    collapsible: true,
    children: [
      'java-thread-x-overview',
      'java-thread-x-theorty',
      'java-thread-x-thread-basic',
      'java-thread-x-lock-all',
      'java-thread-x-key-synchronized',
      'java-thread-x-key-volatile',
      'java-thread-x-key-final',
      'java-thread-x-juc-overview',
      'java-thread-x-juc-AtomicInteger',
      'java-thread-x-lock-LockSupport',
      'java-thread-x-lock-AbstractQueuedSynchronizer',
      'java-thread-x-lock-ReentrantLock',
      'java-thread-x-lock-ReentrantReadWriteLock',
      'java-thread-x-juc-collection-ConcurrentHashMap',
      'java-thread-x-juc-collection-CopyOnWriteArrayList',
      'java-thread-x-juc-collection-ConcurrentLinkedQueue',
      'java-thread-x-juc-collection-BlockingQueue',
      'java-thread-x-juc-executor-FutureTask',
      'java-thread-x-juc-executor-ThreadPoolExecutor',
      'java-thread-x-juc-executor-ScheduledThreadPoolExecutor',
      'java-thread-x-juc-executor-ForkJoinPool',
      'java-thread-x-juc-tool-countdownlatch',
      'java-thread-x-juc-tool-cyclicbarrier',
      'java-thread-x-juc-tool-semaphore',
      'java-thread-x-juc-tool-phaser',
      'java-thread-x-juc-tool-exchanger',
      'java-thread-x-threadlocal',
    ]
  }, {
    text: 'Java IO/NIO/AIO',
    prefix: 'io/',
    collapsible: true,
    children: [
      'java-io-overview',
      'java-io-basic-category',
      'java-io-basic-design-pattern',
      'java-io-basic-code-inputstream',
      'java-io-basic-code-outputstream',
      'java-io-basic-usage',
      'java-io-model',
      'java-io-bio',
      'java-io-nio',
      'java-io-nio-select-epoll',
      'java-io-aio',
      'java-io-nio-netty',
      'java-io-nio-zerocopy',
    ]
  }, {
    text: 'Java 新特性',
    prefix: 'javaup/',
    collapsible: true,
    children: [
      'java8',
      'java8-stream',
      'java8-optional',
      'java8-default',
      'java8-type-anno',
      'java8-anno-repeat',
      'java8-type',
      'java8-jre',
      'java8-permgen',
      'java8-stampedlock',
      'java8-localdatetime',
      'java8-javafx',
      'java8-others',
      'java-8-up-overview',
      'java9-11',
      'java12-17',
      'java9',
      'java10',
      'java11',
      'java12',
      'java13',
      'java14',
      'java15',
      'java16',
      'java17',
    ]
  }, {
    text: 'Java JVM',
    prefix: 'jvm/',
    collapsible: true,
    children: [
      'java-jvm-x-overview',
      'java-jvm-class',
      'java-jvm-class-enhancer',
      'java-jvm-classload',
      'java-jvm-struct',
      'java-jvm-x-introduce',
      'java-jvm-jmm',
      'java-jvm-gc',
      'java-jvm-gc-g1',
      'java-jvm-gc-zgc',
      'java-jvm-cms-gc',
      'java-jvm-param',
      'java-jvm-oom',
      'java-jvm-oom-offheap',
      'java-jvm-thread-dump',
      'java-jvm-debug-tools-linux',
      'java-jvm-debug-tools-list',
      'java-jvm-oom-tool',
      'java-jvm-agent-arthas',
      'java-jvm-debug-idea',
      'java-jvm-agent-usage',
    ]
  }, {
    text: 'Java 其他',
    prefix: 'others/',
    collapsible: true,
    children: [
      'awesome-java',
      'better-java',
    ]
  }],
  '/develop/': [{
    text: '开发理论与基础',
    collapsible: true,
    children: [
      {
        text: '开发理论',
        prefix: 'spec/',
        collapsible: true,
        children: [
          'dev-x-overview',
          'dev-th-solid',
          'dev-th-cap',
          'dev-th-base',
          'dev-th-acid',
          'dev-microservice-kangwei',
        ],
      },
      {
        text: '开发常用类库',
        prefix: 'package/',
        collapsible: true,
        children: [
          'dev-package-x-overview',
          'dev-package-x-apache-common',
          'dev-package-x-google-guava',
          'dev-package-x-hu-tool',
          'dev-package-x-spring-util',
          'dev-package-x-log',
          'dev-package-x-json',
          'dev-package-x-lombok',
          'dev-package-x-mapstruct',
          'dev-package-x-others',
        ],
      }, {
        text: '正则表达式',
        prefix: 'regex/',
        collapsible: true,
        children: [
          'dev-regex-all',
          'dev-regex-usage',
          'dev-regex-tools',
        ],
      }, {
        text: 'CRON表达式',
        prefix: 'cron/',
        collapsible: true,
        children: [
          'dev-cron-x-usage',
          'dev-cron-x-tools',
        ],
      }, {
        text: '网络协议',
        prefix: 'protocol/',
        collapsible: true,
        children: [
          'dev-protocol-overview',
          'dev-protocol-network-basic',
          'dev-protocol-osi7',
          'dev-protocol-ip',
          'dev-protocol-tcpip',
          'dev-protocol-udp',
          'dev-protocol-http',
          'dev-protocol-dns',
          'dev-protocol-url',
          'dev-protocol-tool-netstat',
          'dev-protocol-tool-tcpdump',
          'dev-protocol-tool-wireshark',
        ],
      }, {
        text: '安全相关',
        prefix: 'security/',
        collapsible: true,
        children: [
          'dev-security-overview',
          'dev-security-x-owasp',
          'dev-security-x-injection',
          'dev-security-x-csrf',
          'dev-security-x-xss',
          'dev-security-x-ddos',
          'dev-security-x-click-hijack',
          'dev-security-y-pratice',
          'dev-security-y-pentest-workflow',
        ],
      },
    ]
  }, {
    text: '开发流程',
    prefix: 'dev-agile/',
    collapsible: true,
    children: [
      'dev-x-overview',
      'dev-th-waterfall-model',
      'dev-th-waterfall-vwxh',
      'dev-th-agile',
      'dev-th-agile-xp',
      'dev-th-agile-scrum',
      'dev-th-agile-kanban',
      'dev-pratice-tdd',
      'dev-pratice-ddd',
      'dev-workflow',
      'dev-lean-enterprise',
    ]
  }, {
    text: '重构技巧',
    prefix: 'refactor/',
    collapsible: true,
    children: [
      'dev-refactor-if-else',
      'dev-refactor-not-null',
    ]
  }, {
    text: '质量保障',
    prefix: 'quality-assurance/',
    collapsible: true,
    children: [
      {
        text: '单元测试',
        collapsible: true,
        children: [
          'unit-test',
          'unit-test-junit',
          'unit-test-junit5',
          'unit-test-mockito',
          'unit-test-junit-idea',
          'unit-test-springboot2',
        ],
      },
      {
        text: '统一风格',
        collapsible: true,
        children: [
          'code-style',
          'code-style-name',
          'code-style-static',
        ],
      }, {
        text: '代码质量',
        collapsible: true,
        children: [
          'quality-control-sonarlint',
        ],
      }, {
        text: '企业级规范',
        collapsible: true,
        children: [
          'code-style-alibaba',
          'code-style-google'
        ],
      },
    ]
  },
  {
    text: '设计模式',
    prefix: 'design/',
    collapsible: true,
    children: [
      'thought',
      'seven-principles',
      'uml-class-diagram',
      'summary',
      {
        text: '创建型模式',
        collapsible: true,
        children: [
          'single',
          'factory',
          'prototype',
          'builder'
        ],
      }, {
        text: '结构型模式',
        collapsible: true,
        children: [
          'adapter',
          'bridge',
          'decorator',
          'composite',
          'facade',
          'flyweight',
          'proxy',
        ],
      }, {
        text: '行为型模式',
        collapsible: true,
        children: [
          'template-method',
          'command',
          'visitor',
          'iterator',
          'observer',
          'mediator',
          'memento',
          'interpreter',
          'state',
          'strategy',
          'responsibility',
        ],
      },
      'end'
    ]
  },
  {
    text: '算法和数据结构',
    collapsible: true,
    prefix: 'algorithms-structures/',
    children: [{
      text: '数据结构基础',
      collapsible: true,
      children: [
        'alg-basic-overview',
        'alg-basic-array',
        'alg-basic-linklist',
        'alg-basic-hashtable',
        'alg-basic-stack_queue',
        'alg-basic-tree',
        'alg-basic-tree-search',
        'alg-basic-tree-balance',
        'alg-basic-tree-redblack',
        'alg-basic-tree-hafman',
        'alg-basic-tree-trie',
        'alg-basic-graph',
        'alg-basic-graph-bfs-dfs',
        'alg-basic-graph-min-tree',
        'alg-basic-graph-min-distance',
        'alg-basic-graph-topo-sort',
        'alg-basic-graph-aoe',
      ],
    }, {
      text: '常见排序算法',
      collapsible: true,
      children: [
        'alg-sort-overview',
        'alg-sort-x-bubble',
        'alg-sort-x-fast',
        'alg-sort-x-insert',
        'alg-sort-x-shell',
        'alg-sort-x-select',
        'alg-sort-x-heap',
        'alg-sort-x-merge',
        'alg-sort-x-bucket',
        'alg-sort-x-radix',
      ],
    }, {
      text: '算法思想',
      collapsible: true,
      children: [
        'alg-core-overview',
        'alg-core-divide-and-conquer',
        'alg-core-dynamic',
        'alg-core-greedy',
        'alg-core-devide-two',
        'alg-core-search',
        'alg-core-backtracking',
      ],
    }, {
      text: '领域算法',
      collapsible: true,
      children: [
        'alg-domain-overview',
        'alg-domain-security-degist',
        'alg-domain-security-secure',
        'alg-domain-security-sm',
        'alg-domain-char-match',
        'alg-domain-char-match-bf',
        'alg-domain-char-match-kmp',
        'alg-domain-char-match-bm',
        'alg-domain-char-match-st',
        'alg-domain-bigdata-overview',
        'alg-domain-bigdata-devide-and-hash',
        'alg-domain-bigdata-bloom-filter',
        'alg-domain-bigdata-bucket',
        'alg-domain-bigdata-db-index',
        'alg-domain-bigdata-outsort',
        'alg-domain-bigdata-map-reduce',
        'alg-domain-distribute-overview',
        'alg-domain-distribute-x-consistency-hash',
        'alg-domain-distribute-x-paxos',
        'alg-domain-distribute-x-raft',
        'alg-domain-distribute-x-zab',
        'alg-domain-id-snowflake',
        'alg-domain-load-balance',
        'alg-domain-suggest',
        'alg-domain-machine',
      ],
    }, {
      text: '其他算法相关',
      collapsible: true,
      children: [
        'alg-other-mind',
      ],
    }]
  }, {
    text: '开源协议',
    collapsible: true,
    prefix: 'opensource/',
    children: [
      'dev-x-overview',
      'dev-opensource',
      'dev-agpl',
      'dev-knowledge',
      'dev-mulan',
    ]
  }, {
    text: '系统认证',
    collapsible: true,
    prefix: 'certificate/',
    children: [
      'dev-x-overview',
      'cert-cmm',
      'cert-dengbao',
      'cert-iso27001',
    ]
  }
  ],
  '/db/': [{
    text: '数据库基础和原理',
    prefix: 'sql/',
    collapsible: true,
    children: [
      'sql-db',
      'sql-db-howitworks',
      'sql-db-theory-concept',
      'sql-db-theory-design',
      'sql-db-theory',
    ]
  }, {
    text: 'SQL语言',
    prefix: 'sql-lan/',
    collapsible: true,
    children: [
      'sql-lan',
      'sql-lan-pratice',
      'sql-lan-leetcode',
      'sql-lan-optimize',
    ]
  }, {
    text: 'SQL-MySQL',
    prefix: 'sql-mysql/',
    collapsible: true,
    children: [
      'sql-mysql-overview',
      'sql-mysql-theory',
      'sql-mysql-engine',
      'sql-mysql-b-tree',
      'sql-mysql-performance',
      'sql-mysql-devide',
      'sql-mysql-slave',
      'sql-mysql-mvcc',
      'sql-mysql-execute',
      'sql-mysql-sql-parser',
      'sql-mysql-index-improve-mt',
      'sql-mysql-sql-advisor-mt',
      'sql-mysql-sql-costmodel-mt',
      'sql-mysql-xunjian-mt',
    ]
  }, {
    text: 'NoSQL-Redis',
    prefix: 'nosql-redis/',
    collapsible: true,
    children: [
      'db-redis-overview',
      'db-redis-introduce',
      'db-redis-data-types',
      'db-redis-data-type-special',
      'db-redis-data-type-stream',
      'db-redis-x-redis-object',
      'db-redis-x-redis-ds',
      'db-redis-data-type-enc',
      'db-redis-x-rdb-aof',
      'db-redis-x-pub-sub',
      'db-redis-x-event',
      'db-redis-x-trans',
      'db-redis-x-copy',
      'db-redis-x-sentinel',
      'db-redis-x-cluster',
      'db-redis-x-cache',
      'db-redis-x-version-lastest',
      'db-redis-y-monitor',
      'db-redis-x-performance',
      'db-redis-y-weibo',
      'db-redis-y-mt-1',
      'db-redis-z-mianshi',

    ]
  }, {
    text: 'NoSQL-MongoDB',
    prefix: 'nosql-mongo/',
    collapsible: true,
    children: [
      'mongo',
      'mongo-x-basic',
      'mongo-x-ecosystem',
      'mongo-x-usage-1',
      'mongo-x-usage-2',
      'mongo-x-usage-3',
      'mongo-x-usage-4',
      'mongo-x-usage-5',
      'mongo-y-arch',
      'mongo-y-introduce',
      'mongo-y-ds',
      'mongo-y-page',
      'mongo-y-checkpoint',
      'mongo-y-trans',
      'mongo-y-cache',
      'mongo-z-index',
      'mongo-z-rep',
      'mongo-z-sharding',
      'mongo-z-backup',
      'mongo-performance-model',
      'mongo-y-doc',
      'mongo-performance-improve',
      'postgresql-replace',
    ]
  }, {
    text: 'NoSQL-ElasticSearch',
    prefix: 'nosql-es/',
    collapsible: true,
    children: [
      'elasticsearch',
      'elasticsearch-x-introduce-1',
      'elasticsearch-x-introduce-2',
      'elasticsearch-x-install',
      'elasticsearch-x-usage',
      'elasticsearch-x-index-mapping',
      'elasticsearch-x-index-template',
      'elasticsearch-x-dsl-com',
      'elasticsearch-x-dsl-full-text',
      'elasticsearch-x-dsl-term',
      'elasticsearch-x-agg-bucket',
      'elasticsearch-x-agg-metric',
      'elasticsearch-x-agg-pipeline',
      'elasticsearch-y-th-1',
      'elasticsearch-y-th-2',
      'elasticsearch-y-th-3',
      'elasticsearch-y-th-4',
      'elasticsearch-y-peformance',
      'elasticsearch-z-hello',
      'elasticsearch-z-tencent',
      'elasticsearch-z-meituan',
      'elasticsearch-awesome-es',
      'elasticsearch-wrapper-query',
      'elasticsearch-backup',
    ]
  }],
  '/tool/': [{
    text: 'git基础',
    prefix: 'git/',
    collapsible: true,
    children: [
      'overview',
    ]
  }]
})