name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main
      
permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: coldfusionjp/ghaction-checkout-plus@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm.js 环境
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 安装依赖
        run: pnpm i

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          folder: docs/.vuepress/dist

      # - name: 推送至 Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with: # 从源到目的地
      #     source-repo: 'git@github.com:gavin-james/gavin-james.github.io.git' #Github 仓库地址
      #     destination-repo: 'git@gitee.com:gavin-james/gavin-james.git' #Gitee 仓库地址

      # - name: Build Gitee Pages # 步骤5：自动部署到 Gitee Pages
      #   uses: yanglbme/gitee-pages-action@master
      #   with:
      #     # 注意替换为你的 Gitee 用户名
      #     gitee-username: gavin-james
      #     # 注意在 Settings -> Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库地址，仓库名严格区分大小写，一般地址和仓库名一致，如果地址改了，仓库名不改，要以地址为准（地址仅需后缀，即 https://gitee.com/<username>/xxx 的 xxx 即可）
      #     gitee-repo: gavin-james/gavin-james
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: gh-pages
